### ISSUE TITLE
Deliver ejb-api Specification Version update for Jakarta EE 9

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/ejb-api#62]
**Is your feature request related to a problem? Please describe.**
Jakarta EE 9 is the next major release, with the main focus of moving from the ```javax``` namespace to the ```jakarta``` namespace.

**Describe the solution you'd like**
This issue will be used to track the progress of this work effort via the [Jakarta EE 9 Project board](https://github.com/orgs/eclipse-ee4j/projects/17).

**Additional context**
[Jakarta EE Specification Process](https://jakarta.ee/about/jesp/)
[Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#release)
[Eclipse Release Record for Jakarta EE 9](https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/9)

**ToDo**
- [ ] **[Create Eclipse Release Record](https://www.eclipse.org/projects/handbook/#pmi-commands-release) in your respective Jakarta Specification Project.**
 Most Component Release Records will just reference the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan).  But, if your Component deviates at all from the Platform Release Plan, then a description of the changes will be required in the Release Record.
- [ ] **Initiate a ballot for your Jakarta Release Record/Plan.**
 Again, if your component is only doing the required minimum as defined by the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), then no separate ballot is required.  You are already approved.  But, if your component deviates from the Platform Release Plan, then you will need to initiate your own ballot as defined by the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/).
- [ ] **Jakarta-ize your Specification document (if applicable)**
 Many of the Jakarta EE components now have the source for their Specification documents.  It is strongly recommended that these Specification documents are properly updated to represent Jakarta EE instead of Java EE.  Some [helpful instructions are documented](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc) here.
- [ ] **javax -> jakarta Spec updates**
 If your component has Specification source, then all javax package references need to be updated to use jakarta package references.
- [ ] **javax -> jakarta API updates**
 Your component APIs need to move from using the javax namespace to using the jakarta namespace.
- [ ] **Release Candidate (RC) of Jakarta API in Maven Central**
 A Release Candidate of your component API should be pushed to Maven Central as soon as humanly possible.  This will allow other dependent components to utilize your APIs as they are updating their APIs.  Multiple revisions of these Release Candidate APIs are allowed (and probably expected) during the development cycle.
- [ ] **javax -> jakarta TCK updates**
 Your component TCK needs to be updated to use the jakarta namespace.
- [ ] **javax -> jakarta Compatible Implementation updates**
 Your compatible implementation that will be used to demonstrate completeness of the Specification needs to be updated to use the jakarta namespace.
- [ ] **Final Jakarta API available in Staging Repo**
 When ready, your final version of the API needs to be staged to get ready for the PR review and approvals.
- [ ] **Draft Specification and Apidoc PRs ready for review**
 Like we did for Jakarta EE 8, draft PRs need to be created and reviewed in preparation for the final ballots.
- [ ] **Release Review Ballot started**
 Each Jakarta EE component will need to initiate a separate Release Review ballot after proper reviewing has completed.  To be clear, there will not be a blanket Release Review for all of Jakarta EE 9 like we did for the Plan Review.  Each component needs a separate Release Review.

**Comment by kwsutter** [comment]
Can I ask this team to please create and assign the following labels to this Issue?  Thank you!
[Epic]
[wave:5]

**Comment by kwsutter** [comment]
Any activity on this Issue?  According to our [Jakarta EE 9 Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan) and noted in our [project board](https://github.com/orgs/eclipse-ee4j/projects/17#column-7346442), any potential individual Release Plans are required by Feb 1.  Please communicate any hurdles to meeting this goal.  Thanks!

**Comment by hussainnm** [comment]
javax -> jakarta TCK updates is done in eclipse-ee4j/jakartaee-tck/pull/170

**Comment by ederks85** [comment]
Opened #99 for processing "Jakarta-ize your Specification document (if applicable)"

**Comment by hussainnm** [comment]
javax -> jakarta Compatible Implementation updates
https://github.com/eclipse-ee4j/glassfish/pull/22969/commits/ed5e7314030131a0fd3a9ae9f9ef570de0b38783

Currently Glassfish https://github.com/eclipse-ee4j/glassfish/issues/22983 is waiting on RC2 of ejb-api.

**Comment by kwsutter** [comment]
According to status from @ederks85 on the [Community mailing list](https://www.eclipse.org/lists/jakarta.ee-community/msg02201.html), the EJB Spec has been Jakarta-ized for Jakarta EE 9.  I'm marking those items complete.

**Comment by jeanouii** [comment]
Not sure where we are at with this task.
Did a quick check on the javax namespace in TCK and looks good to me

`egrep -h -o  "javax.[^ ;<]+" -R src/com/sun/ts/tests/ejb* | sort | uniq
javax.naming.*
javax.naming.*"
javax.naming.Binding
javax.naming.Context
javax.naming.Context)
javax.naming.InitialContext
javax.naming.InitialContext()
javax.naming.NameClassPair
javax.naming.NameNotFoundException
javax.naming.NamingEnumeration
javax.naming.NamingException
javax.rmi.*
javax.rmi.PortableRemoteObject
javax.sql.*
javax.sql.DataSource
javax.sql.Datasource.
javax.transaction.xa.XAResource
javax.transacton.TransactionRequiredException`

can we put a tick on the related line?

**Comment by hussainnm** [comment]
We still have around 100 test failures in TCK

**Comment by jeanouii** [comment]
Yes it's been actively worked but I was more looking at the javax -> jakarta item in the list.

**Comment by smillidge** [comment]
Yes last one is in an incorrect package
